[package]
name = "vecfixed"
version = "0.1.0"
edition.workspace = true

[dev-dependencies]
criterion = { version = "0.5.1" }

[[bench]]
name = "vector_fixed"
harness = false

[dependencies]
serde.workspace = true
