[package]
name = "emu"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
logger = { path = "../logger" }
macros = { path = "../macros"}
rand = { version = "0.8.5", optional = true}

[dev-dependencies]
pretty_assertions = "1.3.0"
rand = "0.8.5"

[features]
debug = ["rand"]
mode_5 = ["debug"]
mode_4 = ["debug"]
mode_3 = ["debug"]
